function c_D_num = c_D_function(alpha)
%c_D_function
%    c_D_num = c_D_function(ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2026 14:15:09

t2 = sin(alpha);
t3 = pi.^2;
t4 = alpha.^2;
t5 = t2.^2;
t6 = t4.*(2.09e+2./5.0);
t8 = t3.*1.561049382716049e-1;
t7 = -t6;
t9 = tanh(t8);
t10 = t9+1.0;
t12 = t7+t8;
t11 = 1.0./t10;
t13 = tanh(t12);
t14 = t13+1.0;
c_D_num = -(t5.*(9.43e+2./5.0e+2)+1.39e-2).*(t11.*t14-1.0)+t11.*t14.*((t5.*1.72173791)./(cos(alpha).^2.*5.149+3.151e-1)+1.39e-2);
