function c_L_num = c_L_function(alpha)
%c_L_function
%    c_L_num = c_L_function(ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2026 14:15:09

t2 = pi.^2;
t3 = alpha.*2.0;
t4 = alpha.^2;
t5 = sin(t3);
t6 = t4.*1.4e+1;
t8 = t2.*5.228395061728395e-2;
t7 = -t6;
t9 = tanh(t8);
t10 = t9+1.0;
t12 = t7+t8;
t11 = 1.0./t10;
t13 = tanh(t12);
t14 = t13+1.0;
c_L_num = t5.*(t11.*t14-1.0).*(-9.43e+2./1.0e+3)+(t5.*t11.*t14.*1.4928194405e+1)./(cos(alpha).^2.*5.149+3.151e-1);
