function dc_D_dalpha_num = dc_D_dalpha_function(alpha)
%dc_D_dalpha_function
%    dc_D_dalpha_num = dc_D_dalpha_function(ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2026 14:15:10

t2 = cos(alpha);
t3 = sin(alpha);
t4 = pi.^2;
t5 = alpha.^2;
t6 = t3.^2;
t7 = t5.*(2.09e+2./5.0);
t9 = t4.*1.561049382716049e-1;
t8 = -t7;
t10 = tanh(t9);
t11 = t10+1.0;
t13 = t8+t9;
t12 = 1.0./t11;
t14 = tanh(t13);
t15 = t14.^2;
t16 = t15-1.0;
dc_D_dalpha_num = t2.*t3.*t12.*(t10-t14).*(9.43e+2./2.5e+2)-alpha.*t12.*t16.*((t6.*1.72173791)./(t6.*5.149-5.4641)-1.39e-2).*(4.18e+2./5.0)-alpha.*t12.*t16.*(t6.*(9.43e+2./5.0e+2)+1.39e-2).*(4.18e+2./5.0)+t2.*t3.*t12.*1.0./(t2.^2.*5.149+3.151e-1).^2.*(t14+1.0).*1.8815496228062e+1;
