function dc_L_dalpha_num = dc_L_dalpha_function(alpha)
%dc_L_dalpha_function
%    dc_L_dalpha_num = dc_L_dalpha_function(ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2026 14:15:10

t2 = cos(alpha);
t3 = pi.^2;
t4 = alpha.*2.0;
t5 = alpha.^2;
t6 = cos(t4);
t7 = t2.^2;
t8 = sin(t4);
t9 = t5.*1.4e+1;
t11 = t3.*5.228395061728395e-2;
t10 = -t9;
t12 = t7.*5.149;
t13 = tanh(t11);
t14 = t13+1.0;
t16 = t10+t11;
t20 = t12+3.151e-1;
t15 = 1.0./t14;
t17 = tanh(t16);
t21 = 1.0./t20;
t18 = t17+1.0;
t19 = t17.^2;
t22 = t19-1.0;
dc_L_dalpha_num = t6.*(t15.*t18-1.0).*(-9.43e+2./5.0e+2)-alpha.*t8.*t15.*t22.*2.6404e+1+t6.*t15.*t18.*t21.*2.985638881e+1+alpha.*t8.*t15.*t21.*t22.*4.1798944334e+2+t2.*t8.*t15.*t18.*t21.^2.*sin(alpha).*1.5373054598269e+2;
